### ISSUE TITLE
Fix Mastermind link in the students solutions page

### ISSUE THREAD

**Issue by abachi** [CSalois114/project_sinatra_mastermind#2]
Hi Chris, 
I just want to let you know that your [solution link to the Mastermind live app](https://www.theodinproject.com/lessons/sinatra-project#assignment) is broken, it is pointing to
https://dashboard.heroku.com/apps/sinatra-mastermind-chris and I think you want it to be https://sinatra-mastermind-chris.herokuapp.com

**Comment by CSalois114** [comment]
Hi Nasser,
I just submitted a pull request with the correct link. Thanks for the heads
up!
